subcommand-info:
  event:
    join:
      description: "Join the event! Please clear your inventory"
      permission: events.join
    leave:
      description: "Leave the event. You will be returned to your last location"
      permission: events.leave
    # All permissions below are inherited by 'events.manage.*'
    sethere:
      description: "Set the place of the event"
      permission: events.manage.sethere
    start:
      description: "Start the event"
      permission: events.manage.start
    end:
      description: "End the event"
      permission: events.manage.end
    setteam:
      description: "Set a team's spawn using /event setteam <name>"
      permission: events.manage.setteam
    setmode:
      description: "Set the next event mode. Ends current event"
      permission: events.manage.setmode
modes:
  normal:
    spawn: [location]
  random:
    spawn: [teams]
  salmon:
    spawn: [teams]
    items:
    - salmon
default-mode: normal # matches line 26 key
messages:
  no-permission: "&cYou do not have permission to perform this command."
  player: "You must be a player to perform this action."
  location-set: "&#DDD605Updated event location: &b{0}" # {0} = location
  empty-inventory: "&cPlease empty your inventory before joining the event."
  joining:
    self: "&7&oYou &7have joined the event"
    announce: "&6&l{0} &6has joined the event" # {0} = player name
    already-in: "&cYou are already in the event!"
  leaving:
    self: "&bLeaving the event. You have been returned to your previous location."
    announce: "&6&l{0} &6has left the event" # {0} = player name
    not-in: "&cYou are not in the event!"
    force-end: "&aThe event ended. You have been returned to your previous location."
  no-event: "&cThere is no event currently running."
  event-running: "An event is in progress!"
  force-start: "You can forcibly stop and start a new event using /event start force"
  event-tp: "Teleporting all players..."
  replaced: "Event replaced. New instance: {0}" # {0} = toString of ServerEvent
  ended: "Event ended."
  started: "Event started. New instance: {0}" # {0) = toString of new ServerEvent